### ISSUE TITLE
大哥，你内置的 SearchView 控件是抄袭别人的吧？怎么都修改版权信息了？

### ISSUE THREAD

**Issue by nekocode** [BaronZ88/MinimalistWeather#1]
@BaronZ88

**Comment by ByronNote** [comment]
这个项目中没用到你说的那个JJSearchView，当时放在项目里面只是看过他的源码后想跑起来看看效果（懒得另开一个新项目，所以放到了WeatherStyle，这个你可以仔细看我的源码），因为当时只研究了JJCSearchView的部分源码，所以我是copy了部分源码过来跑的，不存在改版权的事情。 新的commit中已经删除了。:)
