### ISSUE TITLE
缺少 DaggerHomePageComponent 这个类

### ISSUE THREAD

**Issue by lihongxiangleo** [BaronZ88/MinimalistWeather#10]
![image](https://cloud.githubusercontent.com/assets/12996465/23489789/5d11fee4-ff2f-11e6-8e47-a5533f7ad6e9.png)

![image](https://cloud.githubusercontent.com/assets/12996465/23489798/6e50bc04-ff2f-11e6-9eac-35d83fe94123.png)

**Comment by jp1017** [comment]
just 编译一下 :cry:

**Comment by lihongxiangleo** [comment]
奥奥 抱歉没有看到之前已经 close 掉的 issues
