### ISSUE TITLE
下载jar包失败

### ISSUE THREAD

**Issue by 364089999** [BaronZ88/MinimalistWeather#12]
https://maven.fabric.io/public/io/public/fabric/tools/gradle/1.21.7/gradle-1.21.7.jar download不下来

**Comment by ByronNote** [comment]
需要翻墙的.....

**Comment by 364089999** [comment]
我开了蓝灯 能正常访问google 但是你这个还是下不下来!

**Comment by ByronNote** [comment]
算了，我把Fabric去掉好了，好几个人反馈这个问题了
