### ISSUE TITLE
java.lang.RuntimeException: Unable to start activity ComponentInfo{com.baronzhang.android.weather/com.baronzhang.android.weather.activitiy.WelcomeActivity}: android.content.res.Resources$NotFoundException: File res/drawable/bg_launch_window.xml from drawable resource ID #0x7f020055

### ISSUE THREAD

**Issue by miloDev-android** [BaronZ88/MinimalistWeather#14]
应用安装报异常

**Comment by ByronNote** [comment]
clean后重新build看看

**Comment by wb12581** [comment]
报同样的异常 rebuild 未解决 请问你解决了吗?

**Comment by gallonyin** [comment]
@20141125 @wb12581 
BaseActivity
    @Override
    protected void onCreate(Bundle savedInstanceState) {
        AppCompatDelegate.setCompatVectorFromResourcesEnabled(true);
        super.onCreate(savedInstanceState);
    }

AppCompatDelegate.setCompatVectorFromResourcesEnabled(true);
 It works for me.   : )

**Comment by ByronNote** [comment]
@gallonyin gallonyin同学正解，这是由于Vector的兼容性问题导致的，最近一次提交已经修复，大家更新下代码吧。
