### ISSUE TITLE
关于Okhttp3.6.0严格模式初始化时机

### ISSUE THREAD

**Issue by liqiyin** [BaronZ88/MinimalistWeather#17]
你好，OKhttp版本3.6.0初始化时加入了读操作，Application在oncreate时调用init方法，严格模式下会警告，请问有init方法有没有什么更好的调用时机呢？谢谢！

**Comment by ByronNote** [comment]
初始化如果涉及到磁盘读写或者网络请求等耗时操作，可以放到子线程中或者通过 IntentService 来实现。

**Comment by liqiyin** [comment]
okok ：）
