### ISSUE TITLE
关于分包的问题

### ISSUE THREAD

**Issue by MadnessXiong** [BaronZ88/MinimalistWeather#18]
假如把 BaseActivity写在library的话，那么在BaseActivity访问不到app里的东西，比如 App.getInstance().removeActivity(this);这种一些初始化的操作没法在BaseActivity进行。
请问怎么解决这个问题？
我想了一个办法是在app包里再建一个AppBaseActivity继承BaseActivity去实现，但是觉得不太好，请问下还有更好的实现方式吗？

**Comment by ByronNote** [comment]
BaseActivity 并不一定就要放到 library 这个 Module 的，你完全可以根据自己的情况灵活处理。
