### ISSUE TITLE
关于断言assert

### ISSUE THREAD

**Issue by giantbing** [BaronZ88/MinimalistWeather#19]
在ApiConfiguration类中，您使用了断言，在安卓中推不推荐使用断言呢？

**Comment by tmac1999** [comment]
assert builder != null;  不太能理解 这个断言使用的意义。 我个人理解，如果开启-ea断言检查，那么这个语句差不多等同于
if(builder==null)  throw java.lang.AssertionError
然后程序终止运行。
但是如果不使用这个断言，在后面执行
```
private void initialize(final Builder builder) {
        this.dataSourceType = builder.dataSourceType;
    }
```
也会抛出空指针异常，使程序终止运行。
效果不是一样的吗。。  为何要用断言呢？

**Comment by ByronNote** [comment]
@tmac1999 你看的很仔细，这里的断言是多余的
