### ISSUE TITLE
关于城市管理页面的一点疑问

### ISSUE THREAD

**Issue by ysemylord** [BaronZ88/MinimalistWeather#21]
CityManagerFragment中列表项的点击事件响应直接使用了PreferenceHelper；
即View直接调用了Model层不知道是不是有点不妥。代码如下
        cityManagerAdapter.setOnItemClickListener(new CityManagerAdapter.OnCityManagerItemClickListener() {

            @Override
            public void onItemClick(AdapterView<?> parent, View view, int position, long id) {
                try {
                    PreferenceHelper.savePreference(WeatherSettings.SETTINGS_CURRENT_CITY_ID, weatherList.get(position).getCityId() + "");
                    CityManagerFragment.this.getActivity().finish();
                } catch (InvalidClassException e) {
                    e.printStackTrace();
                }
            }
}

**Comment by ByronNote** [comment]
这里确实是不合适，应该通过 Presenter 来实现
