### ISSUE TITLE
下载下来的demo无法运行

### ISSUE THREAD

**Issue by jarvan11** [BaronZ88/MinimalistWeather#22]
![22](https://cloud.githubusercontent.com/assets/17917973/24946394/56e34c0e-1f95-11e7-9619-32074a5721e6.png)

**Comment by jarvan11** [comment]
解决小米手机Android Studio安装app 报错的问题It is possible that this issue is resolved by uninstalling an existi。。。
http://blog.csdn.net/legend12300/article/details/69864547

**Comment by ByronNote** [comment]
6666666
