### ISSUE TITLE
下载您的开源项目，但是编译后找不到DaggerApplicationComponent这个类。

### ISSUE THREAD

**Issue by WanDa1993** [BaronZ88/MinimalistWeather#23]
是有什么改动，没上传么 。我按包名目录没有找到这个的相关类。

**Comment by WanDa1993** [comment]
但是 是可以运行的。我没用过Dagger不好意思。

**Comment by ByronNote** [comment]
这是 Dagger2 框架在编译期生成的类，你 builder 一下就好了。这个问题已经很多很多人问过了，有什么问题可以先看看过往的 issue 。
