### ISSUE TITLE
关于分包问题的一点疑问

### ISSUE THREAD

**Issue by ysemylord** [BaronZ88/MinimalistWeather#24]
谷歌官方的mvp demo是按照业务分包的，但是本Demo为什么不这么做呢

**Comment by ByronNote** [comment]
不同的情况下可以采用不同的分包策略，对于商业项目由于业务多且负责，可以先根据业务来分包；但是对于这样一个小 Demo 就显得没必要了。你可以仔细看看项目 README 中的介绍。
