### ISSUE TITLE
关于合同类中关于接口ContractView的设计请教

### ISSUE THREAD

**Issue by ysemylord** [BaronZ88/MinimalistWeather#28]
合同类中接口View的抽象方法的设计
是应该以一个逻辑为一个抽象方法呢，
还是应该以对一个控件的调用为一个抽象方法呢？
比如有一个逻辑是给TextView设置的文本为空字符时，则隐藏改TextView

方式一
class View extends Fragment  implements Contract.View{

      void displayMsg(Strint text){
           if(TextUtil.isEmpty(text)){
               mTextView.setVisibility(View.GONE);
               retrun;
          }
          mTextView.setVisibility(View.VISIBLE);
          mTextView.setTextView(text);
     }
}
方式二.
class View extends Fragment  implements Contract.View{

      void displayMsg(Strint text){
          mTextView.setTextView(text);
     }

      void hideTextView(){
           mTextView.setVisibility(View.GONE);
     }
      
     void showTextView(){
          mTextView.setVisibility(View.VISIBLE);
     }
}

**Comment by ByronNote** [comment]
抽象的粒度还是需要结合具体的场景来分析，不过我个人倾向于一个 view 的接口方法对应一块具体的小业务
