### ISSUE TITLE
IndicatorView显示不全

### ISSUE THREAD

**Issue by syuunami** [BaronZ88/MinimalistWeather#29]
只显示三角，而不显示下方的图案　[截图](https://raw.githubusercontent.com/syuunami/BlogPictures/master/device-2017-05-18-145647.png)

**Comment by ByronNote** [comment]
@syuunami 7.0的兼容性问题，正在修复，IndicatorView实现的不太好

**Comment by syuunami** [comment]
期待有新的实现供学习 :+1:

**Comment by syuunami** [comment]
期待有新的实现学习下 :+1:

**Comment by ByronNote** [comment]
已修复

**Comment by syuunami** [comment]
@BaronZ88  看到了你的提交．我觉得其实把原先的onMeasure方法中改为`int desiredHeight = this.getChildAt(0).getMeasuredHeight() + getPaddingTop() + getPaddingBottom();`就可以了

**Comment by ByronNote** [comment]
@syuunami 谢谢你的提议，已修改！你的方案显然更好，这样还减少了 onMeasure 的次数，我犯二了...
