### ISSUE TITLE
第三方库太多  

### ISSUE THREAD

**Issue by huanledoufo** [BaronZ88/MinimalistWeather#30]
看你们的安居客app就使用了非常多的框架，里面有很多冗余的东西，连依赖注入框架就使用两个一样的

**Comment by xxnjdlys** [comment]
作为 demo 还是挺的, 但是实际开发中三方库引的太多会导致应用体积变大 
以demo为例 ![](https://ws2.sinaimg.cn/large/006tKfTcly1fgl2o3etjkj3198050dge.jpg)
方法数已经是 41261个.

**Comment by ByronNote** [comment]
@huanledoufo 安居客有太多的历史包袱，在模块化重构的过程中已经在一步步精简了。

**Comment by ByronNote** [comment]
@SadieYuCN 赞同你的看法，实际开发需要根据具体情况来取舍了。比如对数据库依赖不严重的就没必要采用 ORM 框架了；又例如项目体量没那么大的也没必须选用 Dagger 这类依赖注入框架，学习成本摆在那里。所以还是根据具体情况灵活应对吧。
