### ISSUE TITLE
java 8编译问题

### ISSUE THREAD

**Issue by moonljt521** [BaronZ88/MinimalistWeather#32]
我现在用的as2.3， 使用java8来编译会提示要求开启jack，我看您老的项目里没有设置这个，引用了
'me.tatarka.retrolambda' 插件，  请问这个的作用是 ？

**Comment by ByronNote** [comment]
把你的 JDK 版本换成 7 就好了，retrolambda 是为了在 JDK7 及以下的版本中支持 Lambda 表达式。
