### ISSUE TITLE
直接build app报错 [Error:Execution failed for task ':app:mergeDebugResources'. > Error: java.lang.IllegalStateException: Expected BEGIN_ARRAY but was BEGIN_OBJECT at line 1 column 2]

### ISSUE THREAD

**Issue by gengrui1983** [BaronZ88/MinimalistWeather#36]
Hi Baron

我今天clone了这个git的repo，但是发现在build的时候有下面的错误，能麻烦帮忙看看可能是哪儿我配置错了么？多谢！

![image](https://user-images.githubusercontent.com/5415506/30304583-885c4eae-97b1-11e7-9b18-74bd9fe90f76.png)

AndroidStudio 2.3.3， MacOS

多谢，
Rui

**Comment by gengrui1983** [comment]
Sorry Baron, I just found there was a mistake on my own configuration, thanks anyway.

**Comment by abrahambotros** [comment]
Hi @gengrui1983, what was the mistake and the fix, even if it's unrelated to this repo? I'm getting the same error in a similar context when building. Would you mind sharing? Thanks!
