### ISSUE TITLE
Dagger2

### ISSUE THREAD

**Issue by Littleiii** [BaronZ88/MinimalistWeather#6]
感觉Dagger2用的太少了,MVP的父类可以注入,网络层也可注入,fastjson什么的都可以以bean的形式分装,然后注入

**Comment by ByronNote** [comment]
其实我是不太推荐小型项目使用Dagger2的，包括我们自己的项目中也没引入Dagger2

**Comment by KobeBryant824** [comment]
安居客都没用dragger2,得淘宝京东级别的咯
