### ISSUE TITLE
项目构建不下来

### ISSUE THREAD

**Issue by HycHcl** [BaronZ88/MinimalistWeather#8]
grade版本和sdk位置都没错,卡住了,不会是网卡吧?我是download下来的

**Comment by ByronNote** [comment]
依赖了很多第三方库，需要耐心等待下载。你可以把错误日志贴出来看看

**Comment by cellzer** [comment]
Crashlytics相关配置和代码注释掉就行了，我也不知道为啥连不上fabric家的东西。。。

**Comment by ByronNote** [comment]
被墙了吧.....

**Comment by cellzer** [comment]
我开了全局代理也不行。。。不知道为啥，不过影响不大
