### ISSUE TITLE
DaggerHomePageComponent.java类丢失

### ISSUE THREAD

**Issue by liqiyin** [BaronZ88/MinimalistWeather#9]
你好，DaggerHomePageComponent这个类我一直没找到

**Comment by ByronNote** [comment]
这个是Dagger2生成的类，你需要先Build一下项目，如果不了解Dagger2可以看看我的这篇文章 https://zhuanlan.zhihu.com/p/24454466

**Comment by liqiyin** [comment]
好的，不好意思

**Comment by ByronNote** [comment]
：）
